### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aroberge** [aroberge/ideas#1]
- [x] include codec example
  - [x] Contrast use with import hook
  - [ ] Add code for easy creation of custom codecs
- [x] Include ast example
- [x] Include bytecode example
- [x] Include summary for each example
- [x] Include description of all examples (built from summaries?)
- [ ] Review constants example; see if a custom module might be possible
- [x] Do switch statement example
- [ ] Add call with frames removed and debug option to disable it.
